### ISSUE TITLE
[Feature] Allow StoreNames to contain '/' character

### ISSUE THREAD

**Issue by eolivelli** [linkedin/venice#308]
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the Venice community.

### Feature Request Proposal

Allow StoreNames to contain the '/', or alternatively have a way to map a "storeName" to a set of "PubSub topics" .

### Motivation

> #### What is the use case for this feature?

I am running Venice on Pulsar (via Starlight For Kafka), in Pulsar there is builtin support for Multi-Tenancy.
Topic names are in the form "tenant/namespace/topic".

It would be create to have a storeName in the form tenant/namespace/store and see it publishing its data on Kafka topics like:
tenant/namespace/store_v1,tenant/namespace/store_rt.....an so on.

### Details

The main issue is that everywhere, on ZK and on Helix we use the storename as a "resource" name or as a z-node name.
So using '/' is not possible  because '/' is a path separator.

I am trying with these approaches, all of them seems to be a huge refactor in the code base:
1) Allow users to use '/' in the store name and rewrite it to '.' on all the accesses to Helix and ZK. (keep kafka topics as storeName + XXX)
2) Allow users to use '.' in the store name and rewrite it to '/' on all the accesses to Kafka
3) Leverage the PubSub abstraction to perform 2)

Please note that in Kafka on the server side the character '/' is forbidden, so writing integration tests it basically impossible, you have to start Pulsar instead of Kafka.

Option 1 seems the easiest way to do it, but there are many places to touch and we still leak the store -> topic abstraction in to the fact that the topics are storeName + XXX. 

Option 2 is also doable, but in many places there is the assumption that you can derive the storeName from the Kafka topic name, so it is still a huge change.
But the worst part is that uses will use a name with a convention that is different from Pulsar

Option 3: unfortunately the PubSub abstraction is not implemented everywhere.

Another mid-term alternative would be to introduced the concept of "tenant" into Venice 

### What component(s) does this bug affect?

- [X] `Controller`: This is the control-plane for Venice. Used to create/update/query stores and their metadata.
- [X] `Router`: This is the stateless query-routing layer for serving read requests.
- [X] `Server`: This is the component that persists all the store data.
- [X] `VenicePushJob`: This is the component that pushes derived data from Hadoop to Venice backend.
- [X] `Thin Client`: This is a stateless client users use to query Venice Router for reading store data.
- [X] `Fast Client`: This is a stateful client users use to query Venice Server for reading store data.
- [X] `Da Vinci Client`: This is an embedded, stateful client that materializes store data locally.
- [X] `Samza`: This is the library users use to make nearline updates to store data.
- [X] `Admin Tool`: This is the stand-alone client used for ad-hoc operations on Venice.

**Comment by eolivelli** [comment]
I am currently working on Option 3

**Comment by FelixGV** [comment]
Option 3 may be fine, though should we make the character which is replaced by this configurable? I guess it's fine to pick whatever if starting off with this, but if trying to start using this functionality after the fact, then it may not work well to rely on some hardcoded assumption (unless it's a weird one, e.g. `$slash$` or whatever)?

**Comment by eolivelli** [comment]
I think that a good way to achieve 3 is:
- complete the refactor of referring to PubSubTopic everywhere
- let PubSubTopic interface have a "getResourceName" method.

This way when we need a "resourceName" that has a limited set of possible characters (because it is a znode path or an helix resource) we use PubSubTopic#getResourceName().

The PubSub implementation will map the PubSub in any way it wants.

We can build a Kafka based implementation that extends/wraps the current implementation but applies the Topic name mapping as I need.

In the mid term we can have a native Pulsar implementation

**Comment by FelixGV** [comment]
Ok so Pulsar with Starlight would have one implementation, and raw Pulsar another?

What you're proposing SGTM at a high level, but I'd like to get some input from other contributors. I'll try to get some attention on it. Thanks!

**Comment by asaxena76** [comment]
It seems the high level idea that you are proposing is that storename should be hierarchical. That makes sense. I like the idea of using . as a seperator to denote that. Sounds more modern that "/" . The service providers -  pubsub , helix , zookeeper etc. should manage their own namespaces however it works best for them. They will have the responsibility of conversions from and to store names and rest of the venice system shouldn't need to worry about it.  Concrete implementations of PubSub should likewise be free to chose how to map. That is I think the ideal state.  In other words PubSubTopic shouldn't be in the business of how the helix and zookeeper resources should look like. That is for those services to manage, I feel. Otherwise the proposal sounds good. Thanks.

**Comment by gaojieliu** [comment]
@eolivelli 
Supporting a hierarchical store name in Venice is not desired from my understanding.
Inside Venice, there is already logic to guarantee the store name unique across many clusters and there is a mapping between store and the cluster defined already, and that is how Venice supports multi-tenancy today.

The proposal mentioned here is mainly to support multi-tenancy in pub-sub cluster, not Venice, so I think it should be transparent to how Venice itself manages stores.
Let me share one example:
Venice is using Helix/ZK besides Kafka, and what if Helix and Zookeeper want to support the multi-tenancy in the same way as proposed here, shall we add Helix namespace and ZK namespace into Venice store name as well? This won't work well or may not work at all.
Here is what I am thinking:
1. Keep Venice store name convention as it is.
2. Build an abstract layer for the mapping between Venice Store Name and pub-sub topic.
3. Pulsar should implement such mapping management, and Pulsar can choose whatever way/name it needs to use.
4. When extracting the Venice store name from the topic name, we need to talk to this specific mapping implementation instead of assuming the topic name is always `store_name_vxx` or `store_name_rt`.

What do you think?

**Comment by gaojieliu** [comment]
@eolivelli
It seems your latest idea is quite similar to what I shared, and there is no need to change the Venice store name convention, but just build a mapping layer for each pub-sub implementation.

**Comment by FelixGV** [comment]
I guess the ideal solution depends on what is the scope of uniqueness desired for store names.

The current design is to support multi-tenancy within a single organization. Therefore, the scope of uniqueness is global. A tenant cannot create a new store if it collides with a store already created by another tenant. This is what made sense to us when we originally designed Venice for our needs.

I believe, based on slack conversations, that what Enrico is after is a situation where each tenant is fully isolated, and therefore they should not be prevented from creating a given store name even if another tenant already has the same store name for themselves. If that is indeed what Enrico is trying to achieve, then he needs to either:

1. Have the tenant information as part of the Venice store name, so that Venice's global uniqueness does not let different tenants collide with one another, without changing the current implementation. Or,
2. Venice needs to have a first-class notion of namespace such that the scope of uniqueness is per namespace.

**Comment by gaojieliu** [comment]
Yeah, it is good to clarify the requirement.
When talking about the multi-tenancy in Pulsar, what does it exactly mean?
Does it mean the Venice setup is a tenant of a shared Pulsar cluster? And to avoid the collide from other topics created by other tenants, which are created for other purposes?

Or

You are thinking a single Venice setup should support multi orgs as @FelixGV mentioned, so that different org can create the same store in the same Venice setup?

The scope is quite different, and I am wondering whether the latter is what you really want or not.

**Comment by eolivelli** [comment]
Currently our need to have multiple tenants share a Venice cluster.

The solution we are adopting is to require the storeName to be in the form of tenant.namespace.storeName.
This way for Venice we still have a global namespace and it is not possible that tenants access the stores of other tenants (assuming that that the tenant name cannot contain the '.') character.
